# -*- coding: utf-8 -*-
"""harvest seven letter words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrGqPn-hQRxRMCjtdMYUTczOlOyvY5O-
"""

File='sample_data/7lwords'
def fileline(file,line):
  f = open(file, 'r')
  for i in range(line):
    f.readline()
  return f.readline()
  f.close()
def fileappend(file,app):
  f = open(file, 'a')
  f.write(app)
  f.close()
def filelen(File):
  f = open(File, "r")
  nonempty_lines = [line.strip("\n") for line in f if line != "\n"]
  line_count = len(nonempty_lines)
  f.close()
  return line_count
fl=filelen(File)
flarr=[]
print(fl)
for i in range(fl):
  flarr.append(fileline(File,i).replace('\n',''))
print(flarr)